### ISSUE TITLE
Exploratory feature engineering

### ISSUE THREAD

**Issue by rmitsch** [univie-datamining-team3/assignment2#19]
Evaluation of which features work best under which circumstances.
E. g.: Max./min./median/... speed/acceleretation, usage of other sensors, using feature vectors weighting several features to yield one scalar distance, ...

**Comment by Lumik7** [comment]
@rmitsch @MoBran 
I added a base line kmeans clustering on the euclidean distance of the total (n2) to compare future efforts for feature engineering against this base line, see [notebook](https://github.com/univie-datamining-team3/assignment2/blob/issue_%2319_feature_engineering/notebooks/4.0-lm-base-line-kmeans.ipynb).

I would also like to merge this current progress with the master, because:
- the base line might be helpful for the distance calculations, etc as well
- I found a problem in preprocessing that we need the trip_id sorted to identify trips consistently, which I
 fixed in this [commit](https://github.com/univie-datamining-team3/assignment2/commit/125a6e3b6f6169d99ad829c480128bb831f23833)
- I added some plotting functions to plot the clustered trips, which might also be helpful to others

if you agree I will merge the current branch with the master.

**Comment by rmitsch** [comment]
That's great, thanks! I agree to the merge. I'll start work on #21 and #20 tomorrow and base it on 125a6e3b6f6169d99ad829c480128bb831f23833.

**Comment by Lumik7** [comment]
@MoBran   Calculate speed, break length, etc features

**Comment by rmitsch** [comment]
Note: [tsfresh](https://github.com/blue-yonder/tsfresh) sounds very interesting. It calculates a lot of time-series features automatically. I'd highly recommend to use it.
If it works decently, we cut down the manual feature engineering (or drop it entirely).

**Comment by rmitsch** [comment]
See [here](https://github.com/blue-yonder/tsfresh/blob/master/notebooks/robot_failure_example.ipynb) for a introduction into how to use tsfresh.

**Comment by Lumik7** [comment]
I have created a bunch of notebooks which all follow the same [template](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/4.0.0-lm-clustering-template.ipynb).

You can view them here:

 - [ 4.0-lm-base-line-kmeans-n2.ipynb](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/4.0-lm-base-line-kmeans-n2.ipynb)
 - [4.0-lm-base-line-kmeans-xyz-scripted.ipynb](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/4.0-lm-base-line-kmeans-xyz-scripted.ipynb)
 - [4.1-lm-kmeans-distances-feature-engineered-n2-all-trips.ipynb](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/4.1-lm-kmeans-distances-feature-engineered-n2-all-trips.ipynb)*
- [4.2-lm-kmeans-feature_engineering-n2-all-trips.ipynb](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/4.2-lm-kmeans-feature_engineering-n2-all-trips.ipynb)
 - [4.2-lm-kmeans-feature_engineering-n2-scripted.ipynb](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/4.2-lm-kmeans-feature_engineering-n2-scripted.ipynb)
 - [4.3-lm-kmeans-dtw-scripted.ipynb](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/4.3-lm-kmeans-dtw-scripted.ipynb)*

\* Marked as interesting for further exploration. 

I couldn't finish all the clustering today and I have still another project to do, so maybe another one could do the further clustering? 

If you agree I can merge the progress with master and close this issue?
  

With this we have basically all finished for the submission, we just have to put our results in to the documentation. The results are unfortunately not that good though, tram and metro couldn't be separated properly. The best until now was DTW.

**Comment by Lumik7** [comment]
Branch was merged in this [commit](https://github.com/univie-datamining-team3/assignment2/commit/3cd3a664cd06cc9b8ca388d64a13241624655e1c)
