### ISSUE TITLE
Discuss assignment of upcoming tasks before deadline

### ISSUE THREAD

**Issue by rmitsch** [univie-datamining-team3/assignment2#28]
@Lumik7 @MoBran 12 days until the deadline. I added some issues - our current backlog should cover most of the necessary tasks ahead. Please add those that I didn't think of.

Which preferences do you have regarding the issue assignments?

**Comment by Lumik7** [comment]
I think we should make a list of priorities with the tasks that are mandatory, because we do not have that much time left:
Here is an incomplete suggestion:

1) Gather all remaining trips (see issue #1)
2) Find good clustering for "n2" and "x,y,z,"(only scripted) segments
3) Write Documentation. We shouldn't neglect this, because I do not think that they will read the code in detail or look through all the jupyter notebooks
4) Make a presentation with key results

**Comment by Lumik7** [comment]
I think we should make a list of priorities with the tasks that are mandatory, because we do not have that much time left:
Here is an incomplete suggestion:

1) Gather all remaining trips
2) Find good clustering for "n2" and "x,y,z,"(only scripted) segments
3) Write Documentation. We shouldn't neglect this, because I do not think that they will read the code in detail or look through all the jupyter notebooks
4) Make a presentation with key results

**Comment by rmitsch** [comment]
I'd add feature engineering to that list (might be covered by your second point). I think we opened issues representing all of those points, hence I'd suggest to close this issue.

**Comment by Lumik7** [comment]
agree
